### ISSUE TITLE
updating style returns 422 error

### ISSUE THREAD

**Issue by spara** [felt/felt-python#11]
example code

```
null_island = fp.upload_file(
    map_id = map_id,
    file_name = "null_island.geojson",
    layer_name = "Null Island"
)

ni_layer_id = null_island["layer_id"]

urrent_style = fp.get_layer_details(
    map_id=map_id,
    layer_id=ni_layer_id
)

new_style = current_style.copy()
new_style["color"] = "#FF0000"
new_style["size"] = 60
print("Style: ", new_style)

fp.update_layer_style(
    map_id=map_id,
    layer_id=ni_layer_id,
    style=new_style
)

```

Returns the following error:

```
Style:  {'id': 'uBcnG2XRRcG7M9Cc1ercJID', 'links': {'self': '/api/v2/maps/2jX0YV9AXTNeEhIU0Cfge0C/layers/uBcnG2XRRcG7M9Cc1ercJID'}, 'name': 'Null Island', 'status': 'processing', 'type': 'layer', 'progress': 0, 'style': {}, 'geometry_type': None, 'hide_from_legend': False, 'subtitle': '', 'ordering_key': 1, 'color': '#FF0000', 'size': 60}
Traceback (most recent call last):
  File "/Users/sophiaparafina/git/spara/felt/map.py", line 55, in <module>
    fp.update_layer_style(
  File "/Users/sophiaparafina/git/spara/felt/venv/lib/python3.11/site-packages/felt_python/layers.py", line 202, in update_layer_style
    response = make_request(
               ^^^^^^^^^^^^^
  File "/Users/sophiaparafina/git/spara/felt/venv/lib/python3.11/site-packages/felt_python/api.py", line 45, in make_request
    return urllib.request.urlopen(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

**Comment by ChrisLoer** [comment]
Hi @spara the expected input for "style" is a Felt Style Language document (see docs at https://developers.felt.com/felt-style-language/intro). It looks like you're passing in the entirety of the `get_layer_details` response. The existing style is in the `style` field returned from `get_layer_details`, although you'll notice it's empty `{}` since in your case the file hasn't finished uploading yet (so it hasn't been given a default style).

A good way to get the FSL you want to use is to style something the way you want it in Felt, then click "Actions / Edit Styles" in the overflow menu -- you'll see the FSL for that style, and you can use that as a template for your API usage.

**Comment by arredond** [comment]
Ah, I see where the confusion comes from. We have a bad example in our Readme which used a now-depreacted function (`get_layer_style`), which returned the FSL dictionary directly.

I've updated it to use `get_layer_details()["style"]` in [this PR](https://github.com/felt/felt-python/pull/13)
